"""Initial schema

Revision ID: 8298195cb51e
Revises: 
Create Date: 2026-07-07 12:09:59.990396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8298195cb51e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('author_id', sa.Integer(), server_default=sa.text('identity()'), nullable=False),
    sa.Column('author_name', sa.String(length=256), nullable=False),
    sa.Column('author_info', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('author_id'),
    schema='books_data'
    )
    op.create_index('authors_author_name_idx', 'authors', ['author_name'], unique=False, schema='books_data', postgresql_using='gin', postgresql_ops={'author_name': 'gin_trgm_ops'})
    op.create_table('genres',
    sa.Column('genre_id', sa.SmallInteger(), server_default=sa.text('identity()'), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('genre_id'),
    sa.UniqueConstraint('title'),
    schema='books_data'
    )
    op.create_table('languages',
    sa.Column('language_id', sa.SmallInteger(), server_default=sa.text('identity()'), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('language_id'),
    sa.UniqueConstraint('title'),
    schema='books_data'
    )
    op.create_table('publishers',
    sa.Column('publisher_id', sa.SmallInteger(), server_default=sa.text('identity()'), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('link', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('publisher_id'),
    sa.UniqueConstraint('name'),
    schema='books_data'
    )
    op.create_table('organisations',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.SmallInteger(), server_default=sa.text('identity()'), nullable=False),
    sa.Column('organisation_name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['clients.users.user_id'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('organisation_id'),
    sa.UniqueConstraint('organisation_name'),
    sa.UniqueConstraint('owner_id'),
    schema='clients'
    )
    op.create_index('organisations_owner_id_idx', 'organisations', ['owner_id'], unique=False, schema='clients')
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), server_default=sa.text('identity()'), nullable=False),
    sa.Column('login', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('nickname', sa.String(length=512), nullable=False),
    sa.Column('organisation_id', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('LENGTH(login) >= 6', name='users_login_check'),
    sa.ForeignKeyConstraint(['organisation_id'], ['clients.organisations.organisation_id'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('login'),
    schema='clients'
    )
    op.create_index('users_organisation_id_idx', 'users', ['organisation_id'], unique=False, schema='clients')
    op.create_table('subscribe_types',
    sa.Column('id', sa.SmallInteger(), server_default=sa.text('identity()'), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('info', sa.String(length=512), nullable=True),
    sa.Column('price', postgresql.MONEY(), server_default='0', nullable=False),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price >= 0', name='subscribe_types_price_check'),
    sa.PrimaryKeyConstraint('id'),
    schema='subscribes_data'
    )
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), server_default=sa.text('identity()'), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('year_of_publish', sa.SmallInteger(), nullable=False),
    sa.Column('publisher_id', sa.SmallInteger(), nullable=False),
    sa.Column('language_id', sa.SmallInteger(), nullable=False),
    sa.Column('age_rating', sa.Enum('ALL', 'SIX', 'TWELVE', 'SIXTEEN', 'EIGHTEEN', name='age_rating_enum', schema='public'), nullable=True),
    sa.Column('price', postgresql.MONEY(), server_default='0.00', nullable=False),
    sa.Column('text_url', sa.String(length=256), nullable=True),
    sa.Column('cover_url', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price >= 0::money', name='books_price_check'),
    sa.CheckConstraint('year_of_publish BETWEEN 0 AND EXTRACT(YEAR FROM CURRENT_DATE)', name='books_year_of_publish_check'),
    sa.ForeignKeyConstraint(['language_id'], ['books_data.languages.language_id'], initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['publisher_id'], ['books_data.publishers.publisher_id'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('book_id'),
    schema='books_data'
    )
    op.create_index('books_language_id_idx', 'books', ['language_id'], unique=False, schema='books_data')
    op.create_index('books_price_idx', 'books', ['price'], unique=False, schema='books_data')
    op.create_index('books_publisher_id_idx', 'books', ['publisher_id'], unique=False, schema='books_data')
    op.create_index('books_title_idx', 'books', ['title'], unique=False, schema='books_data', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_table('personal_data',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('phonenumber', sa.String(length=20), nullable=True),
    sa.Column('surname', sa.String(length=256), nullable=True),
    sa.Column('first_name', sa.String(length=256), nullable=True),
    sa.Column('second_name', sa.String(length=256), nullable=True),
    sa.Column('payment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("email ~ '^([\\w]+[.-]{0,1}[\\w]+)+@([a-zA-Z0-9]+([.-])*[a-zA-Z0-9]+)+\\.+[a-zA-Z]{2,}$'", name='ck_personal_data_email'),
    sa.CheckConstraint("phonenumber ~ '^\\+\\d{11,15}$'", name='ck_personal_data_phone'),
    sa.CheckConstraint('email IS NOT NULL OR phonenumber IS NOT NULL', name='email_or_phone_required'),
    sa.ForeignKeyConstraint(['user_id'], ['clients.users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phonenumber'),
    schema='clients'
    )
    op.create_index('personaldata_payment_idx', 'personal_data', ['payment'], unique=False, schema='clients', postgresql_using='gin')
    op.create_table('cheques',
    sa.Column('cheque_id', sa.Integer(), server_default=sa.text('identity()'), nullable=False),
    sa.Column('user_id', sa.SmallInteger(), nullable=False),
    sa.Column('total_cost', postgresql.MONEY(), nullable=False),
    sa.Column('cheque_info', sa.String(length=128), nullable=False),
    sa.Column('cheque_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_cost >= 0::money', name='cheques_total_cost_check'),
    sa.ForeignKeyConstraint(['user_id'], ['clients.users.user_id'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('cheque_id'),
    schema='payments_data'
    )
    op.create_index('cheques_cheque_date_idx', 'cheques', ['cheque_date'], unique=False, schema='payments_data')
    op.create_index('cheques_user_id_idx', 'cheques', ['user_id'], unique=False, schema='payments_data')
    op.create_table('contracts',
    sa.Column('contract_id', sa.Integer(), server_default=sa.text('identity()'), nullable=False),
    sa.Column('subscribe_id', sa.SmallInteger(), nullable=False),
    sa.Column('organisation_id', sa.SmallInteger(), nullable=False),
    sa.Column('total_cost', postgresql.MONEY(), nullable=False),
    sa.Column('start_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('contract_info', sa.String(length=256), nullable=True),
    sa.Column('contract_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.CheckConstraint('end_date > start_date', name='contracts_end_date_check'),
    sa.CheckConstraint('start_date >= contract_date AND contract_date <= CURRENT_DATE', name='contract_date_logic'),
    sa.CheckConstraint('total_cost >= 0::money', name='contracts_total_cost_check'),
    sa.ForeignKeyConstraint(['organisation_id'], ['clients.organisations.organisation_id'], initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['subscribe_id'], ['subscribes_data.subscribe_types.id'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('contract_id'),
    schema='payments_data'
    )
    op.create_index('contracts_contract_date_idx', 'contracts', ['contract_date'], unique=False, schema='payments_data')
    op.create_index('contracts_end_date_idx', 'contracts', ['end_date'], unique=False, schema='payments_data')
    op.create_index('contracts_organisation_id_idx', 'contracts', ['organisation_id'], unique=False, schema='payments_data')
    op.create_index('contracts_subscribe_id_idx', 'contracts', ['subscribe_id'], unique=False, schema='payments_data')
    op.create_table('author_book',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['books_data.authors.author_id'], ondelete='CASCADE', initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books_data.books.book_id'], ondelete='CASCADE', initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('author_id', 'book_id'),
    schema='books_data'
    )
    op.create_table('book_genre',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books_data.books.book_id'], ondelete='CASCADE', initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['books_data.genres.genre_id'], ondelete='CASCADE', initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('book_id', 'genre_id'),
    schema='books_data'
    )
    op.create_table('books_changeable',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), server_default='0.00', nullable=True),
    sa.Column('watched', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('rating >= 0.00 AND rating <= 5.00', name='rating'),
    sa.CheckConstraint('watched >= 0', name='watched'),
    sa.ForeignKeyConstraint(['book_id'], ['books_data.books.book_id'], ondelete='CASCADE', initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('book_id'),
    schema='books_data'
    )
    op.create_index('idx_books_changeable_rating', 'books_changeable', ['rating'], unique=False, schema='books_data')
    op.create_index('idx_books_changeable_watched', 'books_changeable', ['watched'], unique=False, schema='books_data')
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), server_default=sa.text('identity()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(length=4096), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 0.00 AND rating <= 5.00', name='reviews_rating_check'),
    sa.ForeignKeyConstraint(['book_id'], ['books_data.books.book_id'], initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['clients.users.user_id'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('review_id'),
    sa.UniqueConstraint('user_id', 'book_id', name='reviews_user_id_book_id_key'),
    schema='books_data'
    )
    op.create_index('reviews_created_at_idx', 'reviews', ['created_at'], unique=False, schema='books_data')
    op.create_index('reviews_rating_idx', 'reviews', ['rating'], unique=False, schema='books_data')
    op.create_table('user_book',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False),
    sa.CheckConstraint('percentage >= 0.00 AND percentage <= 100.00', name='user_book_percentage_check'),
    sa.ForeignKeyConstraint(['book_id'], ['books_data.books.book_id'], ondelete='CASCADE', initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['clients.users.user_id'], ondelete='CASCADE', initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('user_id', 'book_id'),
    schema='books_data'
    )
    op.create_table('cheque_book',
    sa.Column('cheque_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books_data.books.book_id'], initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['cheque_id'], ['payments_data.cheques.cheque_id'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('cheque_id', 'book_id'),
    schema='payments_data'
    )
    op.create_table('cheque_contract',
    sa.Column('cheque_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cheque_id'], ['payments_data.cheques.cheque_id'], initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['payments_data.contracts.contract_id'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('cheque_id', 'contract_id'),
    sa.UniqueConstraint('cheque_id'),
    sa.UniqueConstraint('contract_id'),
    schema='payments_data'
    )
    op.create_table('subscribe_book',
    sa.Column('subscribe_id', sa.SmallInteger(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books_data.books.book_id'], ondelete='CASCADE', initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['subscribe_id'], ['subscribes_data.subscribe_types.id'], ondelete='CASCADE', initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('subscribe_id', 'book_id'),
    schema='subscribes_data'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribe_book', schema='subscribes_data')
    op.drop_table('cheque_contract', schema='payments_data')
    op.drop_table('cheque_book', schema='payments_data')
    op.drop_table('user_book', schema='books_data')
    op.drop_index('reviews_rating_idx', table_name='reviews', schema='books_data')
    op.drop_index('reviews_created_at_idx', table_name='reviews', schema='books_data')
    op.drop_table('reviews', schema='books_data')
    op.drop_index('idx_books_changeable_watched', table_name='books_changeable', schema='books_data')
    op.drop_index('idx_books_changeable_rating', table_name='books_changeable', schema='books_data')
    op.drop_table('books_changeable', schema='books_data')
    op.drop_table('book_genre', schema='books_data')
    op.drop_table('author_book', schema='books_data')
    op.drop_index('contracts_subscribe_id_idx', table_name='contracts', schema='payments_data')
    op.drop_index('contracts_organisation_id_idx', table_name='contracts', schema='payments_data')
    op.drop_index('contracts_end_date_idx', table_name='contracts', schema='payments_data')
    op.drop_index('contracts_contract_date_idx', table_name='contracts', schema='payments_data')
    op.drop_table('contracts', schema='payments_data')
    op.drop_index('cheques_user_id_idx', table_name='cheques', schema='payments_data')
    op.drop_index('cheques_cheque_date_idx', table_name='cheques', schema='payments_data')
    op.drop_table('cheques', schema='payments_data')
    op.drop_index('personaldata_payment_idx', table_name='personal_data', schema='clients', postgresql_using='gin')
    op.drop_table('personal_data', schema='clients')
    op.drop_index('books_title_idx', table_name='books', schema='books_data', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('books_publisher_id_idx', table_name='books', schema='books_data')
    op.drop_index('books_price_idx', table_name='books', schema='books_data')
    op.drop_index('books_language_id_idx', table_name='books', schema='books_data')
    op.drop_table('books', schema='books_data')
    op.drop_table('subscribe_types', schema='subscribes_data')
    op.drop_index('users_organisation_id_idx', table_name='users', schema='clients')
    op.drop_table('users', schema='clients')
    op.drop_index('organisations_owner_id_idx', table_name='organisations', schema='clients')
    op.drop_table('organisations', schema='clients')
    op.drop_table('publishers', schema='books_data')
    op.drop_table('languages', schema='books_data')
    op.drop_table('genres', schema='books_data')
    op.drop_index('authors_author_name_idx', table_name='authors', schema='books_data', postgresql_using='gin', postgresql_ops={'author_name': 'gin_trgm_ops'})
    op.drop_table('authors', schema='books_data')
    # ### end Alembic commands ###
